spring:
  profiles:
    active:
      - dev

---
server:
  port: 8208
spring:
  profiles: dev
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8209
spring:
  profiles: test
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/

